---
  # - name: install apache and tomcat and connector
  #   hosts: myself
  #   remote_user: vagrant
  #   become: yes
  #   become_user: root
  #   roles:
  #     - common
  #     - apache

  - name: install apache and tomcat and connector
    hosts: tomcat
    remote_user: imank
    become: yes
    become_user: root
    roles:
      - tomcat
